### ISSUE TITLE
Always getting error "no such file or directory"

### ISSUE THREAD

**Issue by rafmst** [planety/logue#1]
![image](https://user-images.githubusercontent.com/924985/91662967-1c83d180-eae6-11ea-9cd4-e8bbc4fcd136.png)

I tried on linux using WSL, and on windows and both times got the same type of error, any idea how to fix? Maybe I'm doing something wrong

**Comment by ringabout** [comment]
Now I use strings directly, hope to solve your problem.

**Comment by rafmrs** [comment]
Perfect, amazing job. 👍  thanks for fixing it so quick

**Comment by rafmst** [comment]
Perfect, amazing job. 👍 thanks for fixing it so quick
